spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clearDocs_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update


#  elasticsearch:
#    rest:
#      uris: http://localhost:9200
#    indices:
#      create: true





  mail:
    host: smtp.gmail.com
    port: 587
    username: manishkchoudhary9650@gmail.com
#    password: ejaszgymhoqaneao
    password: fqujsdfvrtczsmch
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true