version: '3.8'  
services:
  elasticsearch:
    image: elasticsearch:7.17.0  # Upgraded version
    container_name: elasticsearch
    restart: "no"
    volumes:
      - ./data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node    
      cluster.name: elasticsearch
      xpack.security.enabled: "false"  # Disable security for easier setup (can be enabled later)
    ports:
      - '9200:9200'
    networks:
      - default_network

  kibana:
    image: kibana:7.17.0  # Upgraded version
    container_name: kibana
    restart: "no"       
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200  
    depends_on:
      - elasticsearch  
    networks:
      - default_network      

networks:
  default_network:
    external: true

